# MIT License
#
# Copyright (c) 2025 @enolgor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3'

dotenv: ['.env']

tasks:
  setup:
    cmds:
      - go install github.com/google/go-licenses@latest
      - go install github.com/google/addlicense@latest
  add-license:
    cmds:
      - addlicense -c "@enolgor" -f LICENSE -l mit -s .
  licenses:*:
    vars:
      MODULE: "{{ index .MATCH 0}}"
    cmds:
      - |
        go install github.com/google/go-licenses@latest
        cd {{.MODULE}}
        {{if eq OS "windows"}}
        wsl sh -c "rm THIRD_PARTY_LICENSES.md || true"
        {{else}}
        rm THIRD_PARTY_LICENSES.md || true
        {{end}}
        echo "# Third Party Licenses" >> THIRD_PARTY_LICENSES.md
        echo "" >> THIRD_PARTY_LICENSES.md
        echo "- [github.com/golang/freetype](https://github.com/golang/freetype/blob/master/licenses/ftl.txt) FreeTypeLicense" >> THIRD_PARTY_LICENSES.md
        go-licenses report --template=../.other/licenses.tpl --ignore golang.org --ignore github.com/enolgor/pdfsigner --ignore github.com/golang/freetype . >> THIRD_PARTY_LICENSES.md
  version:*:
    vars:
      MODULE: "{{ index .MATCH 0}}"
    desc: 'Get the last version of a module'
    cmds:
      - |
        {{if eq OS "windows"}}
        wsl sh -c "git fetch --tags"
        wsl sh -c "git tag --list '{{.MODULE}}/v*' --sort=-v:refname | head -n 1"
        {{else}}
        git fetch --tags
        git tag --list '{{.MODULE}}/v*' --sort=-v:refname | head -n 1
        {{end}}
  release:*:*:
    vars:
      MODULE: "{{ index .MATCH 0}}"
      VERSION: "{{ index .MATCH 1}}"
    desc: 'Create a release for a module'
    cmds:
      - |
        git tag -a '{{.MODULE}}/{{.VERSION}}' -m 'Release {{.MODULE}} {{.VERSION}}'
        git push origin '{{.MODULE}}/{{.VERSION}}'