// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['app']['App']['ChangePassword'](arg1);
}

export function GetFallbackLang() {
  return window['go']['app']['App']['GetFallbackLang']();
}

export function GetLang() {
  return window['go']['app']['App']['GetLang']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsLocked() {
  return window['go']['app']['App']['IsLocked']();
}

export function OpenDB(arg1) {
  return window['go']['app']['App']['OpenDB'](arg1);
}

export function ReadTest() {
  return window['go']['app']['App']['ReadTest']();
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SetLang(arg1) {
  return window['go']['app']['App']['SetLang'](arg1);
}

export function Settings() {
  return window['go']['app']['App']['Settings']();
}

export function Translations() {
  return window['go']['app']['App']['Translations']();
}

export function WriteTest(arg1) {
  return window['go']['app']['App']['WriteTest'](arg1);
}
