// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1:string):Promise<void>;

export function GetFallbackLang():Promise<string>;

export function GetLang():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsLocked():Promise<boolean>;

export function OpenDB(arg1:string):Promise<void>;

export function ReadTest():Promise<string>;

export function SaveSettings(arg1:Record<string, string>):Promise<Record<string, string>>;

export function SetLang(arg1:string):Promise<void>;

export function Settings():Promise<Record<string, string>>;

export function Translations():Promise<Record<string, Record<string, string>>>;

export function WriteTest(arg1:string):Promise<void>;
