// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {certs} from '../models';
import {stamps} from '../models';

export function ChangePassword(arg1:string):Promise<void>;

export function DeleteCertificate(arg1:string):Promise<void>;

export function FirstRunCompleted():Promise<void>;

export function GetCertificateID(arg1:string,arg2:string):Promise<certs.StoredCertificateID>;

export function GetDefaultCertificate():Promise<certs.StoredCertificate>;

export function GetFallbackLang():Promise<string>;

export function GetLang():Promise<string>;

export function GetStoredCertificateID(arg1:string):Promise<certs.StoredCertificateID>;

export function Greet(arg1:string):Promise<string>;

export function IsFirstRun():Promise<boolean>;

export function IsStoreLocked():Promise<boolean>;

export function IsStoreProtected():Promise<boolean>;

export function ListCertificates():Promise<Array<string>>;

export function ListFonts():Promise<Record<string, Array<string>>>;

export function NewDefaultStampConfig():Promise<stamps.StampConfig>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function ReadTest():Promise<string>;

export function SaveSettings(arg1:Record<string, string>):Promise<Record<string, string>>;

export function SetDefaultCertificate(arg1:string):Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function SetUnsavedStamp(arg1:stamps.StampConfig):Promise<void>;

export function Settings():Promise<Record<string, string>>;

export function StoreCertificate(arg1:string,arg2:string):Promise<void>;

export function StoreLogo(arg1:string):Promise<string>;

export function Translations():Promise<Record<string, Record<string, string>>>;

export function UnlockStore(arg1:string):Promise<void>;

export function WriteTest(arg1:string):Promise<void>;
