// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['app']['App']['ChangePassword'](arg1);
}

export function DeleteCertificate(arg1) {
  return window['go']['app']['App']['DeleteCertificate'](arg1);
}

export function FirstRunCompleted() {
  return window['go']['app']['App']['FirstRunCompleted']();
}

export function GetCertificateID(arg1, arg2) {
  return window['go']['app']['App']['GetCertificateID'](arg1, arg2);
}

export function GetFallbackLang() {
  return window['go']['app']['App']['GetFallbackLang']();
}

export function GetLang() {
  return window['go']['app']['App']['GetLang']();
}

export function GetStoredCertificateID(arg1) {
  return window['go']['app']['App']['GetStoredCertificateID'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsFirstRun() {
  return window['go']['app']['App']['IsFirstRun']();
}

export function IsStoreLocked() {
  return window['go']['app']['App']['IsStoreLocked']();
}

export function IsStoreProtected() {
  return window['go']['app']['App']['IsStoreProtected']();
}

export function ListCertificates() {
  return window['go']['app']['App']['ListCertificates']();
}

export function NewDefaultStampConfig() {
  return window['go']['app']['App']['NewDefaultStampConfig']();
}

export function OpenFileDialog(arg1) {
  return window['go']['app']['App']['OpenFileDialog'](arg1);
}

export function ReadTest() {
  return window['go']['app']['App']['ReadTest']();
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SetDefaultCertificate(arg1) {
  return window['go']['app']['App']['SetDefaultCertificate'](arg1);
}

export function SetLang(arg1) {
  return window['go']['app']['App']['SetLang'](arg1);
}

export function Settings() {
  return window['go']['app']['App']['Settings']();
}

export function StoreCertificate(arg1, arg2) {
  return window['go']['app']['App']['StoreCertificate'](arg1, arg2);
}

export function Translations() {
  return window['go']['app']['App']['Translations']();
}

export function UnlockStore(arg1) {
  return window['go']['app']['App']['UnlockStore'](arg1);
}

export function WriteTest(arg1) {
  return window['go']['app']['App']['WriteTest'](arg1);
}
