// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFallbackLang() {
  return window['go']['main']['App']['GetFallbackLang']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Translations() {
  return window['go']['main']['App']['Translations']();
}
